# Generated by Django 6.0 on 2025-12-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="model3d",
            name="drawing_pdf",
            field=models.FileField(blank=True, upload_to="drawings/"),
        ),
    ]
