# Generated by Django 6.0 on 2026-01-06 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_model3d_drawing_pdf"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assembly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Сборка",
                "verbose_name_plural": "Сборки",
            },
        ),
        migrations.CreateModel(
            name="AssemblyStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "assembly",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="main.assembly",
                    ),
                ),
                (
                    "models_3d",
                    models.ManyToManyField(
                        blank=True, related_name="assembly_steps", to="main.model3d"
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаг сборки",
                "verbose_name_plural": "Шаги сборки",
                "ordering": ["order"],
                "unique_together": {("assembly", "order")},
            },
        ),
    ]
